wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1697227711.059781
    t:
      1:
      - 33
      - 54
      - 55
      - 105
      2:
      - 33
      - 54
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
